export {default as Article} from './article/Articles'
export {default as Brand} from './Brand/Brand'
export {default as CTA} from './cta/CTA'
export {default as Function} from './function/Function'
export {default as Navbar} from './navbar/Navbar'